### ISSUE TITLE
Suggest removal of mkheaders.csh, gptlf.F90.template, gptl.h.template and gptl.inc.template

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#12]
I get what was being attempted with these files. By putting the constants in a shell script (mkheaders.csh) and having it construct the header files for C and fortran, the constants are kept in only one place.

However this is a case when the cure seems worse than the disease. Instead, let's just list the constants twice, once for fortran and once for C. The fortran tests will ensure that they fortran constants match the C constants.

This will reduce the number of files, and reduce the build complexity.

**Comment by jmrosinski** [comment]
Still hoping for a single (C+Fortran) clone capability. Given that, presumably some kind of automated generator guaranteeing identical settings C vs. Fortran would be possible. Maybe I can live with having to set the same thing in 2 places. But I implemented that *.csh script just because of the error-prone nature of having to set things to the same value in multiple locations. Adding to the set of C constants/Fortran parameters is a fairly common need for me, and it's really nice to have a mechanism to guarantee that it's done right.

**Comment by edhartnett** [comment]
The mechanism to make sure it is done correctly is to always a both a C and Fortran test for all new capability. So if you are adding a constant to the C library, add a test. When you add the same constant to the Fortran library, add a test there. This will not only prevent the error of you forgetting to use the same value in both place, it will also prevent any accidental change of values.

Remember in my slideshow for build systems I advised: be normal. What you are doing there is not normal. Lots of teams confront the issue of constants in both C and Fortran, including netCDF, HDF5, and PIO. I suggest we do it the same way they do.

**Comment by jmrosinski** [comment]
Since there are 40 or so constants, I'd rather not have 40 tests to ensure
they match between C and Fortran. Instead, how about a single test that
just goes through all the settings and verifies that Fortran matches C? I'd
be fine with that (and can write it). Might require adding a "testit.c" or
whatever to the Fortran side of things.

**Comment by edhartnett** [comment]
Yes, all tests can be together in one code file, which can just loop through the values, for example, or set them one after another, or whatever is the most convenient way to do it in the test.

When I say add a test, frequently that just means add a few lines of code to an existing test to cover the functionality. Other times you take an existing test, cut and paste part of it, and make some modifications.

When your test file gets too big to work with, then you can just add a new one and continue. For example in the netCDF distributions you will find tst_atts.c, tst_atts2.c, tst_atts3.c, etc. Each contain a large number of tests. Since there are lots of tests for attributes, they are broken up into several files.

**Comment by edhartnett** [comment]
OK, I have added a github issue to the fortran project to make a test for this. I have a PR up now to remove these no-longer needed files.
