### ISSUE TITLE
PMPI not handled correctly

### ISSUE THREAD

**Issue by jmrosinski** [jmrosinski/GPTL#21]
Since pmpi.c has lines that look like e.g.:

int MPI_Send (CONST void *buf, ...)

where CONST is defined either to be either "const" (MPI lib adheres to latest standard) or nothing (MPI lib does not adhere to latest standard), there needs to be something that handles defining the cpp token CONST.

In my old gptl lib, this was done in macros.make.* and then tested in Makefile.

So far I don't have access to an MPI lib that doesn't adhere to the latest standard, so possibly a viable option is to change the pmpi.c code from "CONST" to "const". But if we want to retain ability to use PMPI auto-profiling in older MPI libs, we'll need to handle the ifdef.

Right now I'm confused because configure --enable-pmpi doesn't seem to be defining ENABLE_PMPI, so that may be another problem (that for now I don't know how to fix).

**Comment by edhartnett** [comment]
Is this what MPI_CONST is supposed to refer to?

In the current build, the configure.ac is defining CONST to be "const", just as the old system does:
`AC_DEFINE([CONST], [const], [const])
`
This can be seen in config.h:

```
/* const */
#define CONST const

```
I would suggest that anyone who is trying to time their application with a very old MPI library would be far better served by upgrading  their MPI library. So I would suggest just changing it to "const" everywhere.

However, if you still would like this to be done in the configure, we can do that.

--enable-pmpi does indeed define C macro ENABLE_PMPI and also an automake conditional of the same name. So ENABLE_PMPI can be used in #ifdefs and also Makefile.am files. What makes you think it is not working?

**Comment by jmrosinski** [comment]
My concern is for users of HPC systems on which they don't have root (e.g.
me), not being able to utilize the MPI profiling layer (that's what PMPI is
all about) until they get approval of a help ticket and the new MPI library
actually installed. I'm sure you've heard the complaining in our group
meetings about how long it takes to get simple things like that done.

That said, if it's a PIA to address inside autotools maybe enough time has
passed just changing CONST to const is OK. We can discuss. If we're going
to just change CONST to const I'd rather do it inside of pmpi.c than
config.h.

Ah, maybe it's doing the right thing on my machine. I had expected to see a
"-DENABLE_PMPI" in the build output but it wasn't there. I didn't know it
was in the new file config.h so maybe that's OK.

**Comment by edhartnett** [comment]
For Fortran compiles, you will see -DENABLE_PMPI, for C compiles, check in config.h for all defines.

I agree that changing it in the code file is the correct thing to do. It is no trouble addressing it in autotools if you can tell me what you would like. Right now, we always set CONST to "const". If you can figure out some compile time test to learn of cases when we should not, I'm happy to include it.

That said, build systems should change over time. There may be things that were important 10 years ago, but are not any more, because compilers and libraries have been evolving over time. So feel free to just remove what you think may be out of date, and if some user then comes along and complains, you will know you were wrong, and can put it back in. ;-)

Let me know how you would like to proceed on the CONST/const thing. We can leave it alone, take out CONST altogether, or do a test.

**Comment by jmrosinski** [comment]
Yes I see "make check" is testing pmpi and giving success so I was just
looking in the wrong place for #define HAVE_PMPI

**Comment by jmrosinski** [comment]
Since I can't find a MPI lib that I have access to that doesn't adhere to
the "const" standard, that means we really don't have a way to test it.
Let's just change CONST to const in pmpi.c and remove all the autoconf
checking for it. If it turns out we really need it I should be good enough
at cut and paste in autotools to put it back in.

**Comment by edhartnett** [comment]
OK, done. It's now in PR #8.

**Comment by jmrosinski** [comment]
I'm going to close this since it hasn't been an issue in a long time. Feel free to reopen if it reappears.
