### ISSUE TITLE
Resolve issue of bin directory

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#42]
We have a bin directory in the repo, which is incorrect. It contains:

```
  /home/ed/tmp/GPTL/bin:
  total used in directory 40 available 56065092
  drwxrwxr-x  2 ed ed  4096 Aug 28 07:40 .
  drwxrwxr-x 15 ed ed  4096 Aug 28 07:40 ..
  -rw-rw-r--  1 ed ed   214 May 20 08:37 Makefile.am
  -rw-rw-r--  1 ed ed 15160 Aug 28 07:40 Makefile.in
  -rwxrwxr-x  1 ed ed  4953 May 17 17:14 parsegptlout.pl

```

The Makefile.am is:

```
## This is a automake file, part of the GPTL package.

# This is the automake file for GPTL binaries.
# Ed Hartnett, 5/20/18

# Install script in $(bindir) and distribute it.
dist_bin_SCRIPTS = parsegptlout.pl

```

This will cause parsegptlout.pl to be installed in the install bin directory, and be made executable. Is this what is desired?

If so, lets change the directory name to something other than bin, like scripts.

**Comment by jmrosinski** [comment]
Yes, the script needs to be executable, and is best installed in a place
where it can be executed. Its purpose is when auto-profiling, it converts
addresses to human-readable names. That's why I installed it in ".../bin",
but if ".../scripts" is a more generally acceptable place to install
scripts, I'll defer to your judgement.

**Comment by edhartnett** [comment]
OK, bin is fine. I was just being too picky. Heck with it! ;-)
