### ISSUE TITLE
Add a configure file or update README

### ISSUE THREAD

**Issue by rljacob** [jmrosinski/GPTL#46]
The README says you can just run configure but there is no configure file included with the source.

Either the README should be updated with the correct instructions or a configure file provided.

I recommend adding a configure file.  The full autotools suite is sometimes not available and so the user wont be able to run autoconf.

**Comment by edhartnett** [comment]
No need for that at all. In fact, it would be quite incorrect.

The distributions contain configure.

If you want to build from master, instead of a distribution, you need autotools installed.

**Comment by rljacob** [comment]
Ok that's fine.  Then at least add a "For Developers" section in the README or maybe a pointer to a DEVELOPERS file saying autotools is required and how to start if you just want to build from master with only the included configure.ac.

**Comment by krzikalla** [comment]
Just stumbled in the same pitfall.
But where can I find distributions?

**Comment by jmrosinski** [comment]
Apologies, I've not had a chance to build a proper distribution in some
time now since I haven't been able to justify working on GPTL in my current
job. But that is changing. In the meantime you can try running "autoreconf
-i" to generate a configure script, if you have autotools installed on your
machine. Alternatively, after cloning GPTL, you can do:

% git checkout v5.5.3

That will checkout the latest version of GPTL prior to migration to
autotools. The GPTL code is identical or nearly so to the latest version,
only difference being the addition of autotools.

Jim Rosinski

**Comment by edhartnett** [comment]
Users should get the release from the releases page, where they will find a tarball containing everything needed for the build. The latest release is 5.6.0 and it was released in November. We are planning another release shortly to capture recent fixes and improvements.

Developers should check out from the repo and be prepared to run autoreconf -i.

I will add a "For Develiopers" section to the README after we get the repo migrated to its new home, and have CI turned on.

**Comment by jmrosinski** [comment]
Latest release includes configure now.
