### ISSUE TITLE
Show "untimed" regions in the timer output

### ISSUE THREAD

**Issue by ianhinder** [jmrosinski/GPTL#47]
It would be useful to be able to see how much of a timer with children was not covered by its children.  For example, we might have

```
100 main
25     timer1
30     timer2
```

What I am proposing is that the output be (optionally) augmented with an "untimed" line like this:

```
100 main
25     timer1
30     timer2
45     <untimed>
```

so that we know that there might be parts of the code in main taking up significant time that have not yet been manually instrumented.  There would be a configurable threshold under which untimed time was omitted from the output for clarity.

**Comment by jmrosinski** [comment]
If I'm understanding, you're requesting that GPTL do the math of computing, e.g. in your example, "main - timer1 - timer2" and reporting that as "untimed"? 

There are two problems here. The first is that "timer1" and "timer2" might have other parents in addition to "main" (when this happens it is indicated by a "*" in column 1 of GPTL output). As a consequence, valid output may in fact occur whereby "timer1 + timer2" actually **exceeds** "main", so that the computation "main - timer1 - timer2" as "untimed" would be incorrect (e.g. even be a negative number). A number of people have asked for revisions to GPTL code in which timed regions with multiple parents have their time reported on a **per-parent** basis instead of the current situation which is that their reported time is **inclusive across all parents.** Implementing this would be required before "untimed = main - timer1 - timer2" could be implemented correctly. Modifying code for this per-parent approach is a lot of work, but if someone wants to do it I'd be happy to consider it for adoption.

The other problem as I see it with your suggestion is (again using your example) "untimed" is actually a part of "main", no? So it **is** actually part of a timed region (in this case, "main"), no? I find that confusing, but please let me know if I am misunderstanding your suggestion.

**Comment by ianhinder** [comment]
The first problem I had not appreciated before, and I agree that it would need the per-parent solution to be implemented first.  The per-parent implementation would also be very useful to me.  In the past, I actually implemented a similar system of timers (https://bitbucket.org/eschnett/carpet/src/master/Timers/src/TimerTree.hh?at=master&fileviewer=file-view-default) for C++ in which timers are always associated with the parent timer that was actually running when the timer is started, and I find this more useful.

The second problem I had thought about when I was writing the issue and yes, a different name than "untimed" might be better.  "other", or something.  But since we have to wait for the per-parent timers before this can be implemented, we have a while to think about the best name :)

**Comment by jmrosinski** [comment]
I'm going to close this since adding per-parent timings would be a lot of work and might substantially impact performance. If someone else wants to add this functionality, I'll certainly consider the mods.
