### ISSUE TITLE
reorganization of C code

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#54]
@jmrosinski has noted that all the C code is in one big file, gptl.c, and that we should organize it a little better.

I started this issue to help keep track of the discussion and so we can incrementally move forward on this issue.

Jim, you mentioned breaking the code into 4 pieces? What are they?

**Comment by jmrosinski** [comment]
What made the most sense to me, in addition to the core functionality of
gptl.c (GPTLstart/GPTLstop, etc) was:

1) init_final/. Tasks related to initialization and finalization live here.
If you're not familiar with GPTL details I can list the routines, but it's
around 12.

2) util/ Already exists but some utility routines from gptl.c such as
GPTLenable and GPTLdisable should be added.

3) output/  Surprisingly complicated bunch of files solely devoted to
computation and presentation of results. 16 routines that take up much of
gptl.c

4) getter_funcs/ User-callable functions the user can issue during a run to
retrieve information about the state of any particular timer.

5) threadutil/ This one will be easy to create, especially since it used to
be in a separate file. I moved it into gptl.c for better computational
efficiency, but hopefully now inter-file inlining will make this no longer
necessary.

**Comment by edhartnett** [comment]
OK, good detail! Let's get this repo moved to the new group, and get travis set up for it, so we can make these changes with confidence.

I would suggest that in some cases where you have directories, I would suggest just code files. In other words, gptl.c, init.c util.c output.c, get.c threadutil.c.

Certainly that would be an incremental step. If you want to further move some code files to other directories, and break them up further we can do so.

**Comment by jmrosinski** [comment]
No, flat directory structure is fine. There just isn't enough code there to
warrant multiple subdirs, and that just adds confusion anyway.

Separate subdirs for other capabilities, such as GPU, maybe later. This is
currently on a branch. I spent lots of time at NOAA getting the GPU
capability to work, but was stymied by a bug in NVIDIA's underlying timer,
which to my knowledge still hasn't been fixed.

**Comment by jmrosinski** [comment]
Latest release has at least partially addressed this issue. Rewriting in C++ would help, but that proved unworkable for C and Fortran apps.
