### ISSUE TITLE
Auto-profiling C++ code: issue converting names

### ISSUE THREAD

**Issue by seanmarks** [jmrosinski/GPTL#58]
Hi, everyone,

I'm interested in adding GPTL to auto-profile some C++ codes I'm developing. I was recommended to you by some of the folks at the ORNL LCF team. To learn how to use the library, I decided to start with `example4` from the docs. I've run into some post-processing issues that I hope you can help me resolve.

I'm able to compile and run just fine (though I initially got warnings that `__cyg_profile_func_enter/exit` for `main` is called before `GPTLinitialize`, which I worked around by telling GCC not to instrument `main` with an attribute). However, the addresses printed to `timing.0` don't seem to correspond to any symbols from from the executable (obtained via `nm`). I've tried processing the output using both `test/hex2name.pl` from the repo and my own scripts which attempt to do the same thing.

I'm using GCC with Ubuntu 16.04 on my personal laptop, with OpenMP enabled. I'm happy to provide further information, including build files and such.

`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609`
`git: commit ce2306b862b213b5fe940c28170820b7ce87830a (master)`

Thanks for your time!

Sean

**Comment by jmrosinski** [comment]
You can safely ignore the "enter/exit called before main" warnings. But as you discovered, simply not auto-profiling the main program will get rid of them. They occur because the compiler is attempting to auto-profile "main", which means that GPTLstart is being called before GPTLinitialize, which results in a warning.

Regarding your other issue of unrecognized timer names, I recommend using the latest version of GPTL, which no longer needs "parsegptlout.pl". It converts timer addresses to names on the fly with no post-processing step necessary. This makes things easier on the user, and was necessary with the move to create GPTL as a shared library where UNIX tool "nm" as used by "parsegptlout.pl" no longer works. Perhaps you are already using the autoconf-enabled GPTL (i.e. newest)?

If you are already using a recent version of GPTL, maybe it's C++ name mangling of your application source that is causing the unreadable names? If so, you can run c++filt on interesting lines of output to get the de-mangled names. I didn't include running c++filt as part of GPTL because the de-mangled names can be hugely long.

Hope that helps.

**Comment by seanmarks** [comment]
Hi, Jim,

Thanks for getting back to me. I am using the latest version from the
master branch on GitHub. It is Autotools-enabled; I use autoreconf to
generate the necessary build scripts from the rules provided.

Are you saying that, with the latest GPTL version, even auto-instrumented
code should print out human-readable (albeit mangled) function names? When
I run an auto-instrumented code, there are no human-readable names in the
output files (e.g. from GPTLpr_summary), only hex addresses.

What's more, the addresses printed don't seem to match anything printed by
nm, even after adjusting for any cosmetic differences in the output formats
(e.g. prefixed by 0x or not, leading zeroes).

Best,
Sean

**Comment by jmrosinski** [comment]
Sean;

Sorry for the delay, I was busy with other stuff but have some time over
the next weeks to work on GPTL.

Yes you should get human-readable names in the output. BUT, you need to
compile your code with "-g". Were you doing that? If not, feel free to send
me a reproducer and I'll have a look.

Also, look for updates to GPTL over the next few days/weeks.

Regards,
Jim Rosinski

**Comment by seanmarks** [comment]
Hi, Jim,

No worries. As you can see by my own delayed response, I've been quite busy myself. I've been benefiting greatly in the meantime from GPTL by manually instrumenting my programs. However, I would still like to get to the bottom of my difficulties in auto-instrumenting.

I always compile with debugging symbols (-g). Per your request, I've attached a minimal working example that gives me issues with auto-instrumenting. It's just a simple Makefile and some source code based on your Example 2 for GPTL. For reference, I've included the output files I get when I build and run the test program.

Best,
Sean

[for_jrosinski.tar.gz](https://github.com/jmrosinski/GPTL/files/3773604/for_jrosinski.tar.gz)

**Comment by jmrosinski** [comment]
Hi Sean;

Apologies for the delay in looking at your example. You just need to add "-rdynamic" to LDFLAGS to get it to work properly. I'm not not sure which revision of GPTL you are using, but recent commits include hints from "configure" that this may be necessary.

You may want to consider cloning the latest tag, v7.0.2, and rebuilding that. When I get the time I'll make a formal "release" that won't include the requirement for users to run "autoreconf -i", but I think you're already familiar with the current approach. Note also that for C/C++ codes using MPI, you'll need to "#include" both gptl.h and gptlmpi.h. This was necessary to accommodate proper autoconf procedures.

Regards,
Jim

**Comment by jmrosinski** [comment]
No further issues reported so I'm assuming this issue has been addressed.
