### ISSUE TITLE
gptlpr_summary

### ISSUE THREAD

**Issue by ramanan** [jmrosinski/GPTL#6]
When built with HAVE_MPI the declaration of gptlpr_summary in gptl.h does not have the communicator as an argument. Should the header file be generated at compile time based on the HAVE_MPI to be consistent with pr_summary.c?

**Comment by jmrosinski** [comment]
Yes there are 3 entries that do not have argument types in their prototypes. They all take different arguments depending upon whether MPI is enabled. I decided to use the K&R prototype mechanism (only referring to type of return value) for these functions instead of changing based on HAVE_MPI. I will consider your suggestion. Thank you.

**Comment by jmrosinski** [comment]
This has been fixed in the latest GPTL available from github. The API for MPI-enabled stays the same. But when built WITHOUT MPI support, the API to GPTLpr_summary now looks like the MPI-enabled version. Just pass a random integer in the place of the communicator argument in this case.
