### ISSUE TITLE
pmpi check fails for mvapich2-2.3.4 for all compilers

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [jmrosinski/GPTL#60]
I'm trying to build gptl-8.0.2 on a linux system. It configures and builds fine, but the pmpi test fails for mvapich2 (it works with Intel MPI). I've reproduced the failure with gcc (4.8.5, 8.4.0, 9.3.0, 10.1.0), Intel (18.0.5.274 and 19.0.5.281), and PGI (19.10).

I am configuring with:
```
export CC=mpicc
export CXX=mpicxx
export F77=mpif90
export F90=mpif90
export FC=mpif90
export MPIEXEC=srun
./configure --prefix=/blah/blah/gptl-mpi/8.0.2/gcc/8.4.0/mvapich2/2.3.4 --enable-papi --enable-pmpi --with-mpiexec=srun 
```

In all cases, mvapich2 causes the pmpi test to fail:

```
[Christopher.W.Harrop@Hera:hfe07 xml]$ more ../build/gptl-mpi/8.0.2/intel/18.0.5.274/mvapich2/2.3.4/tests/test-suite.log
======================================
   GPTL 8.0.2: tests/test-suite.log
======================================

# TOTAL: 9
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_par_pmpi_test.sh
==========================


Testing MPI functionality...
GPTL error:GPTLget_wallclock: requested timer MPI_Ssend does not exist (or auto-instrumented?)
/blah/blah/gptl-mpi/8.0.2/intel/18.0.5.274/mvapich2/2.3.4/tests/.libs/pmpi: testing suite of MPI routines for auto-instrumentation via GPTL PMPI layer
MPI support level is MPI_THREAD_SINGLE
/blah/blah/gptl-mpi/8.0.2/intel/18.0.5.274/mvapich2/2.3.4/tests/.libs/pmpi: checking that there is a GPTL entry for MPI routine MPI_Ssend...
```
I have not been able to figure out what is different about mvapich2 that is causing this.  I did see issue #21 but I'm not sure if it's related.

**Comment by jmrosinski** [comment]
Hi Chris I only  just read this issue. Since I'm retired I no longer have access to any supercomputer anywhere, so debugging some of these issues will be a challenge. But I will continue to support GPTL as best I can.

Can you try running configure with the added arg "--disable-shared" and see if that helps at all? In the meantime I will see if I can get mvapich2 installed on my laptop for testing.

**Comment by christopherwharrop-noaa** [comment]
@jmrosinski - I thought you may have moved on... Good for you!  I'll see if building with `--disable-shared` helps and let you know. Thank you for taking the time to respond.

**Comment by jmrosinski** [comment]
BTW for the moment you can add --disable-pmpi to configure and "make check" should work (we hope). But MPI auto-profiling will of course be disabled in the resulting library. I couldn't figure out how to devise a usable test for PMPI availability in configure.ac, so all that --enable-pmpi (the default) does is cause compilation of the GPTL layer that intercepts MPI calls without any testing.

**Comment by jmrosinski** [comment]
I just build GPTL8.0.3 with gcc9.3.0 and linked to mvapich2.3.6 (also built with gcc9.3.0) and all "make check" tests passed, including MPI tests. Interestingly, the build of mvapich2.3.6 with gcc10.3.0 failed because its embedded F77 test calling the same function with different argument types failed. Seems like this SHOULD fail, and I'm not thrilled that mvapich2 innards want to do something like that!

Unless you have further problems with this issue I'll close it.
