### ISSUE TITLE
Is the message always print in get_f_mpi_in_place by accident?

### ISSUE THREAD

**Issue by mayeths** [jmrosinski/GPTL#63]
The new file `get_f_mpi_in_place.F90` contains a message that always prints to stdout: `Address of Fortran MPI_IN_PLACE=...`
https://github.com/jmrosinski/GPTL/blob/a7e79e67718b9a55ae69ae804b2d81ed54c87041/fortran/src/get_f_mpi_in_place.F90#L17-L21
Is this on purpose or by accident? There are hundreds and thousands of lines printed to stdout when testing with 10000+ MPI ranks. Thanks.

**Comment by mayeths** [comment]
I can PR a small patch if this is by accident. :)

**Comment by jmrosinski** [comment]
Thank you for the comment. Yes failing to remove this print after I'd finished debugging the mods was an oversight. If you could submit a PR patch that would be great and I'll take it from there.

Simply removing the print when mpi_get_address succeeds would be simplest. Best to leave the failure print in there. ("else" branch). 

What's happening is Fortran MPI calls that use MPI_IN_PLACE (rare in my experience) need to know the address of this constant in order for GPTL to behave properly. So a warning should still be printed in this case ("else" branch). Perhaps this subroutine should be a function whose return code gets passed up the chain to the user to decide what to do. But that's more work so I've no objection to the simple 1-line fix if you'd prefer.

Thanks again,
Jim Rosinski

**Comment by mayeths** [comment]
Return the `ier` sounds more reasonable, I will implement it in this way. The comment in `mpi_alltoallv` mentions:

https://github.com/jmrosinski/GPTL/blob/a7e79e67718b9a55ae69ae804b2d81ed54c87041/fortran/src/f_wrappers_pmpi.c#L454-L459

I am interested in knowing the meaning of `per MPI complete reference`, it appears that `f_mpi_in_place` is forbidden in both `mpi_alltoall` and `mpi_alltoallv` wrappers. However, Section 6.8 in [MPI 4.0 Standard](https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf) says we can still use the `MPI_IN_PLACE` to shrink memory usage with these interfaces. Maybe it's forbidden in Fortran but available in C?

Also, the `f_mpi_in_place` in f_wrappers_pmpi.c defaults to a negative value `-1` which indicates it's uninitialized:

https://github.com/jmrosinski/GPTL/blob/a7e79e67718b9a55ae69ae804b2d81ed54c87041/fortran/src/f_wrappers_pmpi.c#L81-L87

Should I use a boolean value (like `int is_f_mpi_in_place_inited = 0;`) instead for this semantics if we can't tell the value won't be negative? Section 2.5.4 in the Standard doesn't mention anything about the ranges of named constants.
😃

**Comment by jmrosinski** [comment]
Thanks for doing that research. Yes it appears from what you said that the MPI standard has been revised between the reference I have and the 4.0 standard for those routines. Apparently MPI_IN_PLACE is now allowed in mpi_alltoall() and mpi_alltoallv(). As the GPTL code is written, anyone calling the mpi_alltoall* functions from Fortran with M PI_IN_PLACE in their calls to these routines will abort with a message printed explaining why, even though it should succeed. Fixing that may take some time which I don't expect you to deal with since it will probably require additional queries as to which MPI standard is met in the attached MPI library.

Regarding the mpi_alltoall* functions, in earlier MPI standards, both Fortran and C had that limitation of "MPI_IN_PLACE not allowed" that I mentioned. Recall the issue here only regards Fortran wrapper functions in GPTL. When called from a C application, these routines are not called, and the GPTL routines in C are called directly, which just wrap timing calls to the C versions of the routines in the MPI library. I.e. the GPTL C routines don't need to test for MPI_IN_PLACE since they can just let the MPI library handle the issue. Have a look at src/pmpi.c for the GPTL C code if any of this is unclear.

I guess you could use the "is_inited" approach that you suggested for the logic. I just figured that since -1 is an illegal address value, only the single variable was needed for testing whether the function needed to be called.

**Comment by jmrosinski** [comment]
Thanks for providing the PR. I've merged it since all tests passed and the debug print is gone.
